### ISSUE TITLE
Why not using multiprocessing.Manager().dict() ?

### ISSUE THREAD

**Issue by spaceone** [luizalabs/shared-memory-dict#10]
Hello,

it would be nice if the README would describe the reason for this project.
As there is already `multiprocessing.Manager().dict()` in the stdlib which does the same?!
Is this significantly easier or faster than the multiprocessing library?

**Comment by drgarcia1986** [comment]
Hi @spaceone thanks for the comment.

We create this project to provide an alternative for distributed cache servers (like Redis) for some ephemeral data that we can share between our gunicorn/uwsgi workers across some k8s pods, but still in the experimental stage.

About `multiprocessing.Manager().dict()`, according to [python docs](https://docs.python.org/3/library/multiprocessing.shared_memory.html):

> Sharing data directly via memory can provide significant performance benefits compared to sharing data via disk or socket or other communications requiring the serialization/deserialization and copying of data.

Did you already use `multiprocessing.Manager().dict()` across gunicorn/uWSIG workers? 
I'd love to see some examples and perform some benchmarks.

**Comment by drgarcia1986** [comment]
I think it's not an issue of lib I'll close for now.

**Comment by spaceone** [comment]
Yes, thanks for your answer :-)

**Comment by spaceone** [comment]
btw. I expected `multiprocessing.Manager().dict()` to be shared memory, but it seems it creates a UNIX socket and runs a server in a thread.
I can't give you any benchmarks as I don't work with gunicorn/uWSGI.

**Comment by spaceone** [comment]
Another thing is, that `multiprocessing.Manager().dict()` does not work together with `os.fork()` - One have to use `multiprocessing.Process` to use it.

Quoting from stackoverflow https://stackoverflow.com/a/34683072:

> The issue is that Manager create a process and try to stop it at sys.exit. Since the memory of the process is copied (lazily) during the fork both the parent and the child try to stop the process and wait for it to stop. However, as the exception mention only the parent process can do that. If instead of using os.fork, you use multiprocessing.Process which will spawn a new process which wouldn't try to close the Manager at sys.exit.
