### ISSUE TITLE
warning in Python 3.8/resource_tracker.py:216

### ISSUE THREAD

**Issue by covelus** [luizalabs/shared-memory-dict#13]
/usr/lib/python3.8/multiprocessing/resource_tracker.py:216: UserWarning: resource_tracker: There appear to be 1 leaked shared_memory objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '

If you don't mind, I fixed it locally, I will contribute with my fix

**Comment by drgarcia1986** [comment]
Hi @covelus sorry for the huge delay.
Maybe the best way to do that is to use the finalizer `shared_memory_dict.hooks.free_shared_memory()`.
The `shared_memory.unlink()` will [destroy](https://docs.python.org/3/library/multiprocessing.shared_memory.html#multiprocessing.shared_memory.SharedMemory.unlink) the shared reference, so in a big multiprocess scenario we need to finalize the shared memory only once and not on all `SharedMemoryDict().cleanup()`

**Comment by turicas** [comment]
These warnings are actually a Python bug. [I've created a monkey patch to suppress these warnings](https://bugs.python.org/issue38119#msg388287) while we don't have a release with this issue fixed.

**Comment by zzdgit** [comment]
请问下，这个问题解决了吗？我使用你们你们描述的方案，没有报错了，但是把我执行的行的进程kill了。我是在一个进程池中使用

**Comment by BruceInWAlDEN** [comment]
Do not put too much things in your memory, then it will function well.
