### ISSUE TITLE
Use dict instead of OrderedDict

### ISSUE THREAD

**Issue by cassiobotaro** [luizalabs/shared-memory-dict#17]
**Proposal**

As from version 3.7 of Python, dictionary order is guaranteed in any language implementation, I propose the use of `dict` instead of `OrderedDict`. One of the requirements of the project is that the version of Python must be greater than or equal to 3.8. As a benefit of this proposal, we have the use of a structure that does not need to be imported in any module and that is also optimized, which can lead to performance gains and space allocation.

**Problems**

Even though it inherits from `dict`, `OrderedDict` has some unique methods or with different signatures. For example:

`move_to_end` - is only present in `OrderedDict`, and for cases where the last parameter is False, its implementation using `dict` is complex.

`popitem` - In the `dict` it removes the last element inserted, however in the `OrderedDict it has a parameter last that when False, it removes the first element inserted in the dictionary.

Internally, OrderedDict has a linked list implementation that favors this insertion and removal at the beginning of the map.

**Solution and trade-offs**

Inherit from abc MutableMapping, implementing some missing methods, using dict by composition. One implication of this solution is incompatibility with methods already present and mentioned above. To avoid this, I suggest the depreciation of methods that do not respect the dict interface, assuming they are not the main ones.

After reading [this comment](https://stackoverflow.com/a/1394572) by Alex Martelli I am even more convinced of this solution.

**Comment by drgarcia1986** [comment]
LGTM 👍🏾 
The methods `popitem` and `move_to_end` was used on [cache adapters](https://github.com/luizalabs/shared-memory-dict/tree/main/shared_memory_dict/caches) but was removed in [this commit](https://github.com/luizalabs/shared-memory-dict/commit/a242be100c4bef71f5b611c56b3dc5516f749b17), so there's no problem we can deprecate these methods and change the base class.
