### ISSUE TITLE
how to properly shutdown?

### ISSUE THREAD

**Issue by spaceone** [luizalabs/shared-memory-dict#26]
How should I properly close the shared memory?
My processes end with:
```
/usr/lib/python3/dist-packages/multiprocessing_resource_tracker.py:226: UserWarning: resource_tracker: There appear to be 3 leaked shared_memory objects to clean up at shutdown
  (len(rtype_cache), rtype))
```

**Comment by spaceone** [comment]
@cassiobotaro would be OK, but I don't need a manager.

**Comment by cassiobotaro** [comment]
@spaceone Maybe in #31 we can add `close`, `unlink` and expose `buf` to look like ShareableList.

Another thing is to add in README example calls like [this doc](https://docs.python.org/3/library/multiprocessing.shared_memory.htm).

About the manager, if we follow your approach we are saying that the creator of shared memory is the main process, and the others are secondary. This means that if the main process goes down all the shared memory is freed. I don't know if is good this centralized approach.
